// Generated by CoffeeScript 1.9.3
var canvas, ctx, mouse, onPaint, paint_style, painting;

canvas = document.getElementById("canvas");

ctx = canvas.getContext('2d');

painting = document.getElementById('paint');

paint_style = getComputedStyle(painting);

canvas.width = parseInt(paint_style.getPropertyValue('width'));

canvas.height = parseInt(paint_style.getPropertyValue('height'));

mouse = {
  x: 0,
  y: 0
};

canvas.addEventListener('mousemove', function(e) {
  mouse.x = e.pageX - this.offsetLeft;
  return mouse.y = e.pageY - this.offsetTop;
}, false);

ctx.lineWidth = 3;

ctx.lineJoin = 'round';

ctx.lineCap = 'round';

ctx.strokeStyle = '#00CC99';

canvas.addEventListener('mousedown', function(e) {
  ctx.beginPath();
  ctx.moveTo(mouse.x, mouse.y);
  return canvas.addEventListener('mousemove', onPaint, false);
}, false);

canvas.addEventListener('mouseup', function() {
  return canvas.removeEventListener('mousemove', onPaint, false);
}, false);

onPaint = function() {
  return append_event({
    't': 'draw',
    'coords': {
      'x': mouse.x,
      'y': mouse.y
    }
  });
};

//# sourceMappingURL=input.js.map
