// Generated by CoffeeScript 1.9.3
var loop_time, tick;

loop_time = 1 / 60;

tick = function() {
  var event, events, i, len;
  if (events.length !== 0) {
    console.log('sending ' + events.length + ' events');
  }
  for (i = 0, len = events.length; i < len; i++) {
    event = events[i];
    send(event);
  }
  events = [];
  process_incoming();
  return setTimeout(tick, loop_time);
};

tick();

//# sourceMappingURL=loop.js.map
